// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fa2HO--RU_0ssva5_DWD9qitphHN-0w',
    appId: '1:376843153832:web:82a4998716d41cad2b2d9d',
    messagingSenderId: '376843153832',
    projectId: 'stoklarim-471f0',
    authDomain: 'stoklarim-471f0.firebaseapp.com',
    storageBucket: 'stoklarim-471f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7qCA73j4XDGv4x_86q20M4J8ehgySWc',
    appId: '1:376843153832:android:d8753a288dddcbc22b2d9d',
    messagingSenderId: '376843153832',
    projectId: 'stoklarim-471f0',
    storageBucket: 'stoklarim-471f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIY_3_o_l3f7uIVkEzYC-3gMS-MB3h0eE',
    appId: '1:376843153832:ios:0fde653132e63e622b2d9d',
    messagingSenderId: '376843153832',
    projectId: 'stoklarim-471f0',
    storageBucket: 'stoklarim-471f0.firebasestorage.app',
    iosBundleId: 'com.example.storage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIY_3_o_l3f7uIVkEzYC-3gMS-MB3h0eE',
    appId: '1:376843153832:ios:0fde653132e63e622b2d9d',
    messagingSenderId: '376843153832',
    projectId: 'stoklarim-471f0',
    storageBucket: 'stoklarim-471f0.firebasestorage.app',
    iosBundleId: 'com.example.storage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-fa2HO--RU_0ssva5_DWD9qitphHN-0w',
    appId: '1:376843153832:web:c983bed3f6fdfd062b2d9d',
    messagingSenderId: '376843153832',
    projectId: 'stoklarim-471f0',
    authDomain: 'stoklarim-471f0.firebaseapp.com',
    storageBucket: 'stoklarim-471f0.firebasestorage.app',
  );
}
